<a href="https://colab.research.google.com/github/anjunridegreecollege/Pandas-introduction-/blob/main/INTRODUCTION_TO_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [227]:

# Numpy - Numeric Python
# Most powerful package - Library

# Numpy - Dimensions

# A - One Dimensional Array
# [A,B] || [A
#           B] - Two Dimensional Array - Row || Column

# Three Dimensional

# Array - Storing, Manipulating, Similar Data type

# Faster than any mathematical functions
# convenient compared to other packages
# Memory efficiency
# Support multi dimensional arrays

# speed(Numpy operations) > speed(Lists operations)
# size(Numpy operations) < size(Lists operations)

In [228]:
# Install numpy _ pip3 install numpy // pip install numpy

In [229]:
import numpy as np

In [230]:
# Create a numpy array
# 1D array

arr1D = np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [231]:
# Creating 2D array - Matrix
arr2D = np.array([
    [1,2,3],[4,5,6]
])
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [232]:
# Creating arrays with default values

# Creating matrix with all values of elements as '0'
allZeros = np.zeros((2,3))
print(allZeros)

# Creating matrix with all values of elements as '1'
allOnes = np.ones((2,3))
print(allOnes)

# Creating matrix with all values of elements as 'constant value- n ~ Fill value'
allConstant = np.full((2,3),6)
print(allConstant)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6]
 [6 6 6]]


In [233]:

# Create an identity matrix - I - Square matrix

identity = np.eye(4)
print(identity)

# Identity Matrix - Aii = 1 && Aij = 0
# For all A Belongs to R M×N
# Aij

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [234]:
# Creating random Matrices

# between 0 and 1
rand1 = np.random.rand(3,3)
print(rand1)

# between a and b
rand2 = np.random.randint(10,20,(3,3))
print(rand2)

[[0.05860056 0.26307214 0.37068933]
 [0.66306575 0.95074265 0.47829084]
 [0.05643847 0.57514412 0.70803521]]
[[12 11 10]
 [10 16 17]
 [13 17 11]]


In [235]:
# Array Properties

arr = np.array([[1,2,3,4],[2,3,4,5]])
print(arr)

# Shape or array
print(f'\nThe shape of the array is {arr.shape}')

# Size of array
print(f'The size of the array is {arr.size}')

# Datatype of array
print(f'The Data type of the array is {arr.dtype}')

# Dimensions of array
print(f'The Dimension of the array is {arr.ndim}')

[[1 2 3 4]
 [2 3 4 5]]

The shape of the array is (2, 4)
The size of the array is 8
The Data type of the array is int64
The Dimension of the array is 2


In [236]:
# Indexing and Slicing

# Access the elements in 1D Array
arr = np.array([1,2,3,4])
print(arr)
print(arr[3])

# Slicing the elements
print(arr[0:3])
# Indexing and Slicing

# Slicing the elements
print(arr[0:3])

# Access the element in 2D Array
arr2 = np.array([[1,2,3],[2,3,4]])
print(arr2)
print(arr2[1,1])
print(arr2[0,:]) # first row with all columns
print(arr2[:,0]) # first Column with all rows

[1 2 3 4]
4
[1 2 3]
[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [237]:
# L1 = []
# [L1.append(_) for _ in range(10)]

L1 = np.arange(10,-10,-1)

print(L1)

[10  9  8  7  6  5  4  3  2  1  0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


In [238]:
# Mathematical operations

a = np.array([1,2,3])
b = np.array([3,4,5])

print(f'The sum of a and b is {a+b}')
print(f'The diff of a and b is {a-b}')
print(f'The product of a and b is {a*b}')
print(f'The division of a and b is {a/b}')

The sum of a and b is [4 6 8]
The diff of a and b is [-2 -2 -2]
The product of a and b is [ 3  8 15]
The division of a and b is [0.33333333 0.5        0.6       ]


In [239]:
# Matrix multiplication
b1 = np.array([[1,2,3],[2,3,4]])
b2 = np.array([[5,6],[7,8],[1,3]])

# Dot product __ product=AB __ A m × n __ B n × p
c = np.dot(b1,b2)
print(c)

[[22 31]
 [35 48]]


In [240]:
print(b1)

[[1 2 3]
 [2 3 4]]


In [241]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]


In [242]:

[
   [22,31],
   [35,48]
]

[[22, 31], [35, 48]]

In [156]:
import numpy as np

In [157]:
#Recap
arr=np.array([[1,2,3],[4,5,6]])

In [158]:
type(arr)

numpy.ndarray

In [159]:
#Dot product -m×n||n×p
arr1=np.random.randint(1,2,(3,1))

In [160]:
arr.shape

(2, 3)

In [161]:
arr1.shape

(3, 1)

In [162]:
result=np.dot(arr,arr1)

In [163]:
print(result)

[[ 6]
 [15]]


In [164]:
r1=np.random.randint(10,20,(3,3))

In [166]:
print(r1)

[[13 18 12]
 [19 12 13]
 [17 13 14]]


In [167]:
r2=np.eye(3)

In [168]:
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [169]:
#r1.I
result2=np.dot(r1,r2)

In [171]:
print(result2)

[[13. 18. 12.]
 [19. 12. 13.]
 [17. 13. 14.]]


In [60]:
#M.I=I.M=M

In [61]:
#A.B.!=B.A

In [172]:
#mathematical operations
#+-*/
t1=np.random.randint(3,6,(3,3))
t2=np.random.randint(3,6,(3,3))

In [175]:
print(t1)

[[5 3 5]
 [4 3 3]
 [5 4 3]]


In [177]:
print(t2)

[[4 4 4]
 [4 4 3]
 [3 3 5]]


In [178]:
t3=t1+t2

In [179]:
print(t3)

[[9 7 9]
 [8 7 6]
 [8 7 8]]


In [180]:
#matrix multiplication
result=np.dot(arr,arr1)

In [182]:
print(result)

[[ 6]
 [15]]


In [183]:
# statistical operation
mean=t3.mean()
max=t3.max()

In [186]:
print(mean)

7.666666666666667


In [188]:
print(max)

9


In [190]:
median=np.median(t3)

In [192]:
print(median)

8.0


In [194]:
std=np.std(t3)

In [196]:
print(std)

0.9428090415820634


In [198]:
var=np.var(t3)

In [200]:
print(var)

0.8888888888888888


In [201]:
std*std

0.8888888888888888

In [ ]:
# Trigonometry Functions
#sin(x)
#cos(x)
#tan(x)-sin(x)/cos(x)
#cosec(x)-1/sin(x)
#sec(x)-1/cos(x)
#cot(x)-1/tan(x)

In [203]:
angles=np.array([0,15,30,45,60,75,90])

In [204]:
result=np.sin(np.radians(angles))
result1=np.cos(np.radians(angles))
result2=np.tan(np.radians(angles))

In [205]:
print(result)
print(result1)
print(result2)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [206]:
Searr=np.array([1,2,3,4,5,6])

In [207]:
#Reshape the array.
reshapedarr= arr.reshape(3,2)

In [208]:
print(reshapedarr)

[[1 2]
 [3 4]
 [5 6]]


In [209]:
#convert / flatten any n dim array
flattenedarr = arr.flatten()

In [210]:
print(flattenedarr)

[1 2 3 4 5 6]


In [225]:

#stacking the data
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])
#Vertical stacking
arr3=np.vstack((arr1,arr2))
print(f"The shape of arr3 is{arr3.shape}")
#Horizontal stacking
arr4=np.vstack((arr2,arr3))
print(np.hstack((arr1,arr2)))
print(f"The shape of arr4 is{arr4.shape}")
print(arr4)

The shape of arr3 is(2, 4)
[ 1  2  3  4 10 20 30 40]
The shape of arr4 is(3, 4)
[[10 20 30 40]
 [ 1  2  3  4]
 [10 20 30 40]]


In [226]:
#Filtering the data
arr=np.array([10,20,30,40,50,60,70,80])
farr=arr[arr>40]
print(farr)

[50 60 70 80]
